# Generated by Django 4.0.2 on 2022-09-21 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, unique=True)),
                ('year', models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('MD', 'Middler'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], default='FR', max_length=2)),
                ('college', models.CharField(choices=[('DM', 'BUSINESS'), ('KR', 'COMPUTER_SCIENCE'), ('BV', 'HEALTH'), ('CSSH', 'SOCIAL_SCIENCE'), ('ENG', 'ENGINEER'), ('SC', 'SCIENCE'), ('AMD', 'AMD'), ('OTHER', 'OTHER')], default='OTHER', max_length=20)),
                ('number_coops_completed', models.IntegerField()),
                ('linkedin', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000)),
                ('tags', models.CharField(max_length=10)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coping_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=1000)),
                ('pay', models.DecimalField(decimal_places=2, max_digits=8)),
                ('title', models.CharField(max_length=100)),
                ('co_op_num', models.IntegerField()),
                ('cycle', models.CharField(choices=[('SM', 'Summer'), ('S', 'SPRING'), ('F', 'F')], default=None, max_length=2)),
                ('tasks', models.CharField(max_length=10000)),
                ('drug_test', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coping_app.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coping_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coping_app.post')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coping_app.user')),
            ],
        ),
    ]
