# Generated by Django 4.0.2 on 2022-09-23 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coping_app', '0002_alter_internship_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, unique=True)),
                ('year', models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('MD', 'Middler'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], default='FR', max_length=2)),
                ('college', models.CharField(choices=[('DM', 'BUSINESS'), ('KR', 'COMPUTER_SCIENCE'), ('BV', 'HEALTH'), ('CSSH', 'SOCIAL_SCIENCE'), ('ENG', 'ENGINEER'), ('SC', 'SCIENCE'), ('AMD', 'AMD'), ('OTHER', 'OTHER')], default='OTHER', max_length=20)),
                ('number_coops_completed', models.IntegerField()),
                ('linkedin', models.CharField(max_length=100, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coping_app.customuser'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coping_app.customuser'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
