# Generated by Django 4.0.2 on 2022-09-27 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coping_app', '0004_remove_customuser_user_customuser_last_login_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internship',
            old_name='user',
            new_name='owner',
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(default='company_name', max_length=100),
        ),
    ]
