# Generated by Django 4.0.2 on 2022-09-27 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coping_app', '0006_alter_comment_user_alter_post_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='owner',
        ),
    ]
