# Generated by Django 4.0.2 on 2022-09-27 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coping_app', '0007_rename_user_post_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
