# Generated by Django 4.0.2 on 2022-09-27 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coping_app', '0008_post_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='owner',
        ),
    ]
