# Generated by Django 4.0.2 on 2022-10-22 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coping_app', '0011_alter_comment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='coping_app.post'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='cycle',
            field=models.CharField(max_length=2000),
        ),
    ]
