# Generated by Django 4.0.2 on 2022-10-22 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coping_app', '0012_alter_comment_post_alter_internship_cycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='year',
            field=models.CharField(default='FR', max_length=200),
        ),
    ]
