# Generated by Django 4.0.2 on 2022-10-22 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coping_app', '0013_alter_customuser_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='college',
            field=models.CharField(default='OTHER', max_length=200),
        ),
    ]
