# Generated by Django 4.0.2 on 2022-10-22 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coping_app', '0014_alter_customuser_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=200),
        ),
    ]
